### ISSUE TITLE
ZeroPi does not boot

### ISSUE THREAD

**Issue by silme** [bz31/Buildroot#2]
Booting with the zeropi image hangs at "Starting kernel...". I tried images for both 5.4.31 and 4.19.81 kernel versions.

**Comment by bz31** [comment]
How did you see the message "Starting kernel..." ?

**Comment by silme** [comment]
By connecting with serial console.

**Comment by bz31** [comment]
Have you tested ssh? 
I disabled serial console (I think).

**Comment by silme** [comment]
This is embarrassing... I am always using serial console and did not check ssh. Of course it boots.

**Comment by bz31** [comment]
My goal is to make an network audio player (client), with a minimal Linux system. 
It works with a server and internet and smartphone, I chose ssh and disabled serial console.
